#!/bin/bash

SCALACLASSPATH="target/scala-2.11/leon_2.11-3.0.jar "$(echo ./runtime/*.jar)

case $(uname -o) in 
  Cygwin) 
    SCALACLASSPATH=$(echo $SCALACLASSPATH | tr ' ' ';')
    if [[ $(getconf LONG_BIT) = 64 ]]
    then 
      SCALACLASSPATH="$SCALACLASSPATH;unmanaged/64/scalaz3-win-64b-2.1.jar" 
    else
      echo "Sorry, we don't have a Leon executable for your platform." 1>&2 
      exit 1
    fi
    ;;
  *)
    SCALACLASSPATH=$(echo $SCALACLASSPATH | tr ' ' ':')
    if [[ $(getconf LONG_BIT) = 64 ]]
    then 
      SCALACLASSPATH="$SCALACLASSPATH:unmanaged/64/scalaz3-unix-64b-2.1.jar" 
    else
      SCALACLASSPATH="$SCALACLASSPATH:unmanaged/32/scalaz3_2.10-2.0.jar" 
    fi
    ;;
esac

[[ ! -e /tmp/leon ]] && rm -rf /tmp/leon && ln -s $(pwd)/library/leon /tmp/

#echo $SCALACLASSPATH

java -Xmx2G -Xms512M -classpath ${SCALACLASSPATH} -Dscala.usejavacp=false scala.tools.nsc.MainGenericRunner -classpath ${SCALACLASSPATH} leon.Main $@ 2>&1 | tee -i last.log
